### ISSUE TITLE
Opening specific files causes freeze

### ISSUE THREAD

**Issue by afreakk** [nix-community/tree-sitter-nix#34] opened 2023-01-14 15:33 UTC
Im using this treesitter for neovim, and its been fine until I tried opening:
`pkgs/development/haskell-modules/make-package-set.nix` from `nixpkgs`.

Then neovim froze and started using enourmous amounts of memory until I killed neovim.
This happens every time I open that file using neovim with this treesitter, if I disable the nix treesitter parser it opens fine.  
Not sure how to debug this, so this is not very helpfull, but I could easily reproduce the issue atleast.
```
 ❯ nvim --version
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/dl03s9vbm0i0qqg6sqv37rvd4mghbk6c-neovim-unwrapped-0.8.2/share/nvim
"
```

**Comment by folke** [comment] 2023-01-17 11:13
Same issue on Neovim, with the following minimal file:

```nix
{}: let
in {
  programs.waybar = {
  exec = let
  in
    pkgs.writeShellScript "todo-waybar" ''
      $(${todo} | ${wc} -l)
    '';
  };
}
```

Seems to be caused by the bash parser, byt the injection at line 7, the ` | `

**Comment by cstrahan** [comment] 2023-02-03 22:50
Hmm. That's no good. Thanks for the report!

I'm super swamped at the moment, so if anyone can take a stab at debugging this, it would be greatly appreciated. Otherwise I'll take a look as soon as I have some spare time.

**Comment by folke** [comment] 2023-02-04 06:10
Treesitter has fixed a bug upstream that at least fixed the issue from my minimal nix file.

**Comment by afreakk** [comment] 2023-02-04 08:40
> ```nix
> {}: let
> in {
>   programs.waybar = {
>   exec = let
>   in
>     pkgs.writeShellScript "todo-waybar" ''
>       $(${todo} | ${wc} -l)
>     '';
>   };
> }
> ```
Thats weird, it didnt for me, running `nvim-treesitter (0e6d4b4)`, and disabled all my treesitter plugins like  nvim-hop and  matchup.
Will try a minimal nvim config later with only treesitter and nothing else installed

**Comment by afreakk** [comment] 2023-02-05 15:22
A more minimal example
```
writeShellScript "test" "$(${x}|${y} )"
```
writeShellScript ( `queries/injections.scm:17` ) turns the following string to be:
```
 (#set! injection.language "bash")
 (#set! injection.combined))
```
So when I tried removing my `bash` treesitter parser, it didnt freeze anymore.

**Comment by folke** [comment] 2023-02-06 07:06
The treesitter dep was updated in a very recent nightly Neovim built.

See here: https://github.com/neovim/neovim/pull/21858

**Comment by cstrahan** [comment] 2023-03-22 03:22
I'm fairly certain that this has been resolved upstream, so I'll close this now; if I'm mistaken, ping me and I'll reopen.

**Closed by cstrahan** 2023-03-22 03:22 UTC
